//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimeAcademy.MovieTitles.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LimeAcademy.MovieTitles.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page&quot;:1,&quot;per_page&quot;:10,&quot;total&quot;:0,&quot;total_pages&quot;:0,&quot;data&quot;:[]}.
        /// </summary>
        internal static string JohnyJohnyYesPappaResults {
            get {
                return ResourceManager.GetString("JohnyJohnyYesPappaResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page&quot;:1,&quot;per_page&quot;:10,&quot;total&quot;:13,&quot;total_pages&quot;:2,&quot;data&quot;:[{&quot;Poster&quot;:&quot;https://images-na.ssl-images-amazon.com/images/M/MV5BYjFhN2RjZTctMzA2Ni00NzE2LWJmYjMtNDAyYTllOTkyMmY3XkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_SX300.jpg&quot;,&quot;Title&quot;:&quot;Italian Spiderman&quot;,&quot;Type&quot;:&quot;movie&quot;,&quot;Year&quot;:2007,&quot;imdbID&quot;:&quot;tt2705436&quot;},{&quot;Poster&quot;:&quot;https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ4MzcxNDU3N15BMl5BanBnXkFtZTgwOTE1MzMxNzE@._V1_SX300.jpg&quot;,&quot;Title&quot;:&quot;Superman, Spiderman or Batman&quot;,&quot;Type&quot;:&quot;movie&quot;,&quot;Year&quot;:2011,&quot;imdbID&quot;:&quot;tt2084949&quot;},{&quot;Poste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpidermanResultsPage1 {
            get {
                return ResourceManager.GetString("SpidermanResultsPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;page&quot;:&quot;2&quot;,&quot;per_page&quot;:10,&quot;total&quot;:13,&quot;total_pages&quot;:2,&quot;data&quot;:[{&quot;Poster&quot;:&quot;N/A&quot;,&quot;Title&quot;:&quot;They Call Me Spiderman&quot;,&quot;Type&quot;:&quot;movie&quot;,&quot;Year&quot;:2016,&quot;imdbID&quot;:&quot;tt5861236&quot;},{&quot;Poster&quot;:&quot;N/A&quot;,&quot;Title&quot;:&quot;The Death of Spiderman&quot;,&quot;Type&quot;:&quot;movie&quot;,&quot;Year&quot;:2015,&quot;imdbID&quot;:&quot;tt5921428&quot;},{&quot;Poster&quot;:&quot;https://images-na.ssl-images-amazon.com/images/M/MV5BZDlmMGQwYmItNTNmOS00OTNkLTkxNTYtNDM3ZWVlMWUyZDIzXkEyXkFqcGdeQXVyMTA5Mzk5Mw@@._V1_SX300.jpg&quot;,&quot;Title&quot;:&quot;Spiderman in Cannes&quot;,&quot;Type&quot;:&quot;movie&quot;,&quot;Year&quot;:2016,&quot;imdbID&quot;:&quot;tt5978586&quot;}]}.
        /// </summary>
        internal static string SpidermanResultsPage2 {
            get {
                return ResourceManager.GetString("SpidermanResultsPage2", resourceCulture);
            }
        }
    }
}
